### ISSUE TITLE
Error when fetching updated issues via sync repo button

### ISSUE THREAD

**Issue by aaa006bd** [geprog/CodeCaptain#27]
While trying to fetch the updated issues I have encountered this following error

![image](https://github.com/geprog/codecaptain/assets/3983401/82a24b90-aaf0-448b-ad1b-9f7312df5898)

**Comment by anbraten** [comment]
I guess that issue comes if the cloned repo is somehow not able to merge upstream commits. However I don't know why it can't simply pull them as the local repo should never be touched. We should have an eye if this issue appears again. But for the beginning its probably the easiest if the user could just remove a repo, so he can add it again if its broken.
